### PR TITLE
nx17

### PR DESCRIPTION
**Pull request by beeman**

### CODE REVIEW

**Comment by hassankhan** [comment]
Just adding 2c here, we merged this PR in a private fork and deployed to GitHub Package Registry so we could use it, and it seems to be working pretty well.

**Comment by beeman** [comment]
> Just adding 2c here, we merged this PR in a private fork and deployed to GitHub Package Registry so we could use it, and it seems to be working pretty well.

Thanks for testing and confirming. 

I think I'm going to release this basically as-is so it's at least back to a working state.

**Comment by shyaaam** [comment]
Can you merge this PR then? if there are no further blockers

**Comment by therecluse26** [comment]
image

**Pull request closed without merging**
