### PR TITLE
feat: pass flags and environment variables to go build

### PR DESCRIPTION
**Pull request by phillipCouto**
A few enhancements:

1. Added OS interoperable way of passing environment variables to go build
2. Added ability to pass build flags to build executor
3. Updated executor schema to properly communicate the options and expected types
4. Expanded unit tests to validate new functionality
5. Updated executor options to properly communicate output and main are optional  

This replaces the PR #65

### CODE REVIEW

**Comment by phillipCouto** [comment]
@beeman this superseeds #65 and is more robust.

**Comment by jaredzwick** [comment]
looks awesome, any chance this works with the nx spec for target specific env files?

i.e 
.env.build and .env.serve

**Comment by phillipCouto** [comment]
> looks awesome, any chance this works with the nx spec for target specific env files?
> 
> i.e .env.build and .env.serve

It would be better to handle this as a separate issue that way if you wanted to tackle it you could 😄. If you don't have the time I am more than happy to work on it.

**Comment by phillipCouto** [comment]
@beeman anyway we can get this reviewed?

**Comment by phillipCouto** [comment]
@beeman this also superseeds #80

**Comment by beeman** [comment]
Thanks @phillipCouto - I finally found time to merge this and released it as version 2.8.0.

**Comment by phillipCouto** [comment]
Awesome! Thank you ☺️

**Pull request merged**
