### PR TITLE
feat: don't generate main.go in src folder

### PR DESCRIPTION
**Pull request by beeman**

### CODE REVIEW

**Comment by fallion** [comment]
Is this coming?

**Comment by beeman** [comment]
Hey @fallion , I plan to change this yes, but I need to figure out why this PR breaks the tests.

If you have any idea please let me know!

**Comment by fallion** [comment]
I opened up a second PR where I will attempt to fix it. The issue I see is with where go fmt is being executed. It doesn't support the way you have the command right now, so I will change the `cwd` to be in the project and run `go fmt ./...` there. The same might be needed for tests. See #17

**Comment by beeman** [comment]
> I opened up a second PR where I will attempt to fix it. The issue I see is with where go fmt is being executed. It doesn't support the way you have the command right now, so I will change the `cwd` to be in the project and run `go fmt ./...` there. The same might be needed for tests. See #17

Hey  @fallion , thanks for this, this was spot on. I've now fixed both in #24 and #27.

**Pull request merged**
